---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-6.7
    driver:
      require_chef_omnibus: true
      network:
        - ["public_network", {bridge: 'en0: Wi-Fi (AirPort)'}]
        - ["forwarded_port",{ guest: 2379, host: 5379}]
        - ["forwarded_port",{ guest: 2380, host: 5380}]
        - ["forwarded_port",{ guest: 4001, host: 6001}]
        - ["forwarded_port",{ guest: 7001, host: 9001}]
        - ["forwarded_port",{ guest: 8080, host: 8080}]
suites:
  - name: server
    run_list:
      - recipe[chef-essentials-classroom::install-etcd]
    attributes:
  - name: client
    run_list:
      - recipe[chef-essentials-classroom::build-chef-workstation]
    attributes:
