---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      provider: libvirt
      box: ubuntu14.04
      network:
        - ["forwarded_port",{ guest: 8080, host: 8080}]
suites:
  - name: server
    run_list:
      - recipe[chef-essentials-classroom::build-guac-server]
    attributes:
