name 'chef-essentials-classroom'
maintainer 'Ian Henry'
maintainer_email 'ihenry@chef.io'
license 'all_rights'
description 'Configures Servers for Chef Essentials Classroom'
long_description 'Configures Servers for Chef Essentials Classroom'
version '1.3.0'

depends 'chef-ingredient'
depends 'docker'
depends 'yum-epel'
depends 'apt'
depends 'guacamole'
depends 'etcd'
depends 'confd'
